spring:
  application:
    name: cloud-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
server:
  port: 18088
